<a href="https://colab.research.google.com/github/Giovanni2132/NumberClassificator/blob/main/NumberClassificator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importazione del dataset da openml

In [1]:
import pandas as pd
from google.colab import data_table

data_table.enable_dataframe_formatter()

In [2]:
from sklearn.datasets import fetch_openml
mnist=fetch_openml("mnist_784",version=1)
print(mnist.keys())
print(mnist)

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])
{'data':        pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.

Ora bisogna convertire i dati in un formato che deve essere manipolato in maniera semplice, si creerà la variabile X che avrà le informazioni per quanto riguarda l'immagine, e la y è la variabile che si vuole predire

In [3]:
X,y=mnist["data"],mnist["target"]
print(X.head())
print(y.head())

   pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel781  pixel782  pixel783  pixel784  
0       0.0       

Bisogna convertire la target variable in un intero di 8 bit

In [4]:
import numpy as np
from sklearn import preprocessing

y=y.astype(np.uint8)
classes=y.drop_duplicates().sort_values().tolist()

In [5]:
import pandas as pd


# Converti il dataset in un DataFrame di Pandas
mnist_df = pd.DataFrame(data=mnist.data, columns=mnist.feature_names)
mnist_df['target'] = mnist.target

# Utilizza pd.isna() per contare i valori nulli
nan_mask = mnist_df.isna()
nan_count = nan_mask.sum()

print(nan_count)

pixel1      0
pixel2      0
pixel3      0
pixel4      0
pixel5      0
           ..
pixel781    0
pixel782    0
pixel783    0
pixel784    0
target      0
Length: 785, dtype: int64


In [6]:
print(X.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Columns: 784 entries, pixel1 to pixel784
dtypes: float64(784)
memory usage: 418.7 MB
None


In [7]:
import numpy as np
from tensorflow.keras.datasets import mnist

# Carica il dataset MNIST
(x_train, y_train), (_, _) = mnist.load_data()

# Calcola statistiche di base
mean_pixel_value = np.mean(x_train)
std_pixel_value = np.std(x_train)
min_pixel_value = np.min(x_train)
max_pixel_value = np.max(x_train)

# Stampa delle statistiche
print(f"Media del valore dei pixel: {mean_pixel_value}")
print(f"Deviazione standard del valore dei pixel: {std_pixel_value}")
print(f"Valore minimo del pixel: {min_pixel_value}")
print(f"Valore massimo del pixel: {max_pixel_value}")

11490434/11490434 [==============================] - 0s 0us/step
Media del valore dei pixel: 33.318421449829934
Deviazione standard del valore dei pixel: 78.56748998339798
Valore minimo del pixel: 0
Valore massimo del pixel: 255


Ora si divide il dataset in un testset e un trainingset

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Number transactions X_train dataset: ", X_train.shape)
print("Number transactions y_train dataset: ", y_train.shape)
print("Number transactions X_test dataset: ", X_test.shape)
print("Number transactions y_test dataset: ", y_test.shape)

Number transactions X_train dataset:  (56000, 784)
Number transactions y_train dataset:  (56000,)
Number transactions X_test dataset:  (14000, 784)
Number transactions y_test dataset:  (14000,)


In [12]:
import matplotlib.pyplot as plt
import pandas as pd

pd.value_counts(mnist["target"]).plot.bar()
plt.xlabel('target')
plt.ylabel('Frequency')
mnist["target"].value_counts()

TypeError: 'module' object is not subscriptable

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

num_pipeline=Pipeline([
    ('std_scaler',StandardScaler())
])

X_train_prepared=num_pipeline.fit_transform(X_train)
X_test_prepared=num_pipeline.fit_transform(X_test)

In [22]:
import numpy as np

# Calcola alcune statistiche di sintesi utilizzando NumPy
mean_values = np.mean(X_train_prepared, axis=0)
std_dev_values = np.std(X_train_prepared, axis=0)
min_values = np.min(X_train_prepared, axis=0)
max_values = np.max(X_train_prepared, axis=0)

# Stampa le statistiche
print("Mean:", mean_values)
print("Standard Deviation:", std_dev_values)
print("Minimum:", min_values)
print("Maximum:", max_values)

Mean: [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -1.52259158e-18  0.00000000e+00 -1.52259158e-18 -1.52259158e-18
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  2.03012210e-18  1.26882631e-18  0.00000000e+00
  6.02692499e-18  2.53765263e-18 -6.34413157e-19  4.44089210e-18
 -6.47101420e-18 -6.09036631e-18 -6.34413157e-18  1.09119063e-17
 -1.62409768e-17 -2.28388736e-18  3.55271368e-18 -8.24737104e-18
  4.44089210e-18 -1.01506105e-18  3.80647894e-19 -1.96668079e-18
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.90323947e-19
 -2.03012210e-18 -3

**Random Forest**

In [8]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import make_pipeline

rf_classifier = OneVsRestClassifier(
    make_pipeline(RandomForestClassifier(random_state=42))
)
rf_classifier.fit(X_train_prepared, y_train)

OneVsRestClassifier(estimator=Pipeline(steps=[('randomforestclassifier',
                                               RandomForestClassifier(random_state=42))]))

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import metrics

y_train_pred =  rf_classifier.predict(X_test_prepared)


print(confusion_matrix(y_test, y_train_pred ))


print(classification_report(y_test, y_train_pred ))
print("Accuracy:",metrics.accuracy_score(y_test, y_train_pred ))
print("Precision:",metrics.precision_score(y_test, y_train_pred,average='weighted'))
print("Recall:",metrics.recall_score(y_test, y_train_pred,average='weighted'))

[[1315    0    5    2    1    1    4    1   14    0]
 [   0 1520   15   11    2   11    2    3   36    0]
 [   1    0 1327    7    4    1    4    3   30    3]
 [   1    0   11 1359    1    9    1    9   35    7]
 [   1    0    9    1 1236    1    8    1    9   29]
 [   2    0    1   22    0 1221    8    0   18    1]
 [   4    0    2    0   10   11 1356    0   13    0]
 [   7    1   19    4    8    2    0 1412   11   39]
 [   1    0   11   11    1    4    3    4 1319    3]
 [   5    4    5   16   23    7    0   20   31 1309]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1343
           1       1.00      0.95      0.97      1600
           2       0.94      0.96      0.95      1380
           3       0.95      0.95      0.95      1433
           4       0.96      0.95      0.96      1295
           5       0.96      0.96      0.96      1273
           6       0.98      0.97      0.97      1396
           7       0.97      0.94   

In [10]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import classification_report

NB = BernoulliNB()

NB.fit(X_train_prepared, y_train)

prediction = NB.predict(X_test_prepared)

labels = np.unique(y_test)
print(confusion_matrix(y_test, prediction))

#Overall, how often is the classifier correct?

print(classification_report(y_test, prediction))

print("Accuracy:",metrics.accuracy_score(y_test, prediction))
print("Precision:",metrics.precision_score(y_test, prediction,average='weighted'))
print("Recall:",metrics.recall_score(y_test, prediction,average='weighted'))

[[1198    1    7    3    2   54   43    1   31    3]
 [   0 1525    6    6    1   17    4    1   38    2]
 [  17   28 1131   45   25    7   55   14   53    5]
 [  10   32   63 1161    3   33   13   16   59   43]
 [   5    8    9    1 1014    6   26    3   23  200]
 [  24   21   11  176   34  911   27    5   36   28]
 [  16   38   25    1   20   31 1261    0    4    0]
 [   7   31   10    5   36    2    1 1277   30  104]
 [  14   68   19  100   12   49   12    5 1024   54]
 [  10   31   10   13  100    9    0   49   30 1168]]
              precision    recall  f1-score   support

           0       0.92      0.89      0.91      1343
           1       0.86      0.95      0.90      1600
           2       0.88      0.82      0.85      1380
           3       0.77      0.81      0.79      1433
           4       0.81      0.78      0.80      1295
           5       0.81      0.72      0.76      1273
           6       0.87      0.90      0.89      1396
           7       0.93      0.85   

In [11]:
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

model = SVC(kernel='linear', random_state=42)  # Specifica il kernel (lineare, RBF, polinomiale, ecc.)
model.fit(X_train_prepared, y_train)

# Predizione dei risultati
y_pred = model.predict(X_test)

labels = np.unique(y_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred,labels=labels))


print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred,average='weighted'))
print("Recall:",metrics.recall_score(y_test, y_pred,average='weighted'))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


[[1315    0    4    2    4    1    7    1    8    1]
 [   1 1309    2   14    2    1    1    2  267    1]
 [  23   15 1074   54   39    0   38   14  116    7]
 [  14    3   11 1319    1   11    5    2   59    8]
 [   9    0    3    4 1189    0   11    1   13   65]
 [  99   13   11  208   34  385   34    1  463   25]
 [  18    2   21    2   25    5 1308    0   15    0]
 [  21    2   27  114   48    1    0 1173   39   78]
 [  16    4    3   21    4    1   10    2 1292    4]
 [  15    5    5   34   82    0    0   14   87 1178]]
              precision    recall  f1-score   support

           0       0.86      0.98      0.92      1343
           1       0.97      0.82      0.89      1600
           2       0.93      0.78      0.85      1380
           3       0.74      0.92      0.82      1433
           4       0.83      0.92      0.87      1295
           5       0.95      0.30      0.46      1273
           6       0.93      0.94      0.93      1396
           7       0.97      0.78   